<a href="https://colab.research.google.com/github/tidaltamu/workshop-data/blob/main/beginner/workshop1/code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Beginner Lecture 1

## Python

### Howdy, World!

In [ ]:
print("Howdy, World!")

Howdy, World!


### Numerical Operators

In [ ]:
3 + 3   # addition

6

In [ ]:
8 - 6   # subtraction

2

In [ ]:
7 * 9   # multiplication

63

In [ ]:
5 / 4   # division; results in float, different from Java or C++

1.25

In [ ]:
5 // 4  # integer division

1

In [ ]:
5 % 4   # modulus, results in remainder

1

In [ ]:
2 ** 3

8

### Variables

In [ ]:
# just like algebra, variables can be used to store values
x = 4
x + 3

7

In [ ]:
# operations can be preformed on two or more variables
x = 2
y = 7
x * y

14

In [ ]:
# variables should have meaningful names
num_apples = 32
dozen_apples = num_apples / 12
dozen_apples

2.6666666666666665

In [ ]:
x = 3
x = x + 1
x

4

In [ ]:
x = 3
x += 1
x

4

In [ ]:
x = 3
x -= 1
x

2

In [ ]:
x = 3
x *= 2
x

6

In [ ]:
x = 3
x /= 2
x

1.5

### Data Types

In [ ]:
x = 3
type(x)

int

In [ ]:
x = 4.5
type(x)

float

In [ ]:
x = "Howdy!"
type(x)

str

In [ ]:
# you can use single OR double quotes
"howdy" == 'howdy'

True

In [ ]:
x = True
type(x)

bool

### The `print()` Function

In [ ]:
x = "howdy!"
y = "hello!"
x
y

'hello!'

In [ ]:
x = "howdy!"
y = "hello!"
print(x)
print(y)

howdy!
hello!


In [ ]:
# Print can be used for any data type
x = 3
y = 4.0
z = False
print(x)
print(y)
print(z)

3
4.0
False


### Boolean Operators

In [ ]:
True and True

True

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
True or True

True

In [ ]:
False or False

False

In [ ]:
not True

False

### Relational Operators

In [ ]:
x = 3
y = 4

In [ ]:
x = y   # this is the ASSIGNMENT operator
x

4

In [ ]:
x = 3
x == y

False

In [ ]:
x != y

True

In [ ]:
x < y

True

In [ ]:
x > y

False

In [ ]:
x < 3

False

In [ ]:
x <= 3

True

In [ ]:
y >= 4

True

### Conditional Statements

In [ ]:
num_apples = 8
if num_apples > 6:
  print("That's a lot of apples!")
else:
  print("There aren't very many apples")

That's a lot of apples!


In [ ]:
num = 0
if num < 0:
  print("The number is negative")
elif num == 0:
  print("The number is zero")
else:
  print("The number is positive")

The number is zero


In [ ]:
# nested conditionals
num = 4
if num > 0:
  if num % 2 == 0:  # number is even
    print("The number is positive and even")
  else:
    print("The number is positive and odd")
else:
  print("The number is not positive")

The number is positive and even


### Loops

In [ ]:
i = 0
print("i =", i)
i += 1
print("i =", i)
i += 1
print("i =", i)

i = 0
i = 1
i = 2


In [ ]:
i = 0
while (i < 5):  # cover infinite loops
  print("i =", i)
  i += 1

i = 0
i = 1
i = 2
i = 3
i = 4


In [ ]:
for i in range(5):  # cover when to use while loops vs. for loops, use for loops most often
  print("i =", i)

i = 0
i = 1
i = 2
i = 3
i = 4


### Lists

In [ ]:
my_list = [2, 7, 8, -13, 12]  # initialization

In [ ]:
for i in my_list:   # iteration
  print(i)

2
7
8
-13
12


In [ ]:
len(my_list)

5

In [ ]:
my_list[3]

-13

In [ ]:
my_list[-1]

12

In [ ]:
my_list[1:3]

[7, 8]

In [ ]:
my_list.append(3)
my_list

[2, 7, 8, -13, 12, 3]

In [ ]:
for i in my_list:
  i += 5
my_list

[2, 7, 8, -13, 12, 3]

In [ ]:
for i in range(len(my_list)):
  my_list[i] += 5
my_list

[7, 12, 13, -8, 17, 8]

### Dictionaries

In [ ]:
majors = {"Carson": "Computer Engineering", "Ishaan": "Applied Math/Computer Science"}

In [ ]:
majors["Ishaan"]

'Applied Math/Computer Science'

##NumPy

In [ ]:
import numpy as np

### Arrays

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr2 = np.array([5, 2, 6, 8, 4])  # adding arrays
arr + arr2

array([ 6,  4,  9, 12,  9])

In [ ]:
arr * 3   # multiply array by scalar

array([ 3,  6,  9, 12, 15])

In [ ]:
arr2D = np.array([[1, 2, 3], [4, 5, 6]])
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr2D[:, 0]   # array indexing

array([1, 4])

In [ ]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
arr3D

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [ ]:
arr3D.ndim

3

In [ ]:
arr3D.shape

(2, 2, 3)

In [ ]:
print(arr3D.transpose())
print()
print('original:')
print(arr3D)

[[[1 1]
  [4 4]]

 [[2 2]
  [5 5]]

 [[3 3]
  [6 6]]]

original:
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


### Vectors

In [ ]:
v1 = np.array([[1, 2, 3]])
v2 = np.array([[2],[1],[3]])

print(v1, '\n')
print(v2)

[[1 2 3]] 

[[2]
 [1]
 [3]]


In [ ]:
dot = np.dot(v1, v2)
print(dot)

[[13]]


### Matrices

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [ ]:
matrix*3

array([[ 3,  6],
       [ 9, 12]])

In [ ]:
matrix2 = np.array([[-2, 1], [3/2, -1/2]])
matrix + matrix2  # matrix addition, must have same dimensions

array([[-1. ,  3. ],
       [ 4.5,  3.5]])

In [ ]:
np.matmul(matrix, matrix2)  # matrix multiplication

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.matmul(matrix2, matrix)  # matrix mutiplication is NOT COMMUTATIVE

array([[1., 0.],
       [0., 1.]])

In [ ]:
vector = np.array([[3],
                   [4]])

In [ ]:
np.dot(matrix, vector)  # matrix-vector multiplication

array([[11],
       [25]])

In [ ]:
np.eye(2)   # identity matrix

array([[1., 0.],
       [0., 1.]])

In [ ]:
np.linalg.inv(matrix)   # matrix inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
np.matmul(matrix, np.linalg.inv(matrix))  # a matrix times its inverse is the identity matrix

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [ ]:
matrix = np.array([[1, -2],
                   [-3, 6]])
np.linalg.inv(matrix)   # not every matrix has an inverse!

LinAlgError: ignored